Repository KarmaKamikaze/ChatRPG, pull requests merged in 2023-11, with the labels that each got.

#27 Fix saving
  ChatRPG/ChatRPG/Data/FileUtility.cs
  ChatRPG/ChatRPG/Pages/Campaign.razor
Labels: bug

#36 Feature/open ai api improvements
  ChatRPG/API/HttpClientFactory.cs
  ChatRPG/API/HttpMessageHandlerFactory.cs
  ChatRPG/API/IFoodWasteClient.cs
  ChatRPG/API/IOpenAiLlmClient.cs
  ChatRPG/API/OpenAiLlmClient.cs
  ChatRPG/API/SallingClient.cs
  ChatRPG/Areas/Identity/Pages/Account/LogOut.cshtml
  ChatRPG/Areas/Identity/Pages/Account/Login.cshtml
  ChatRPG/Areas/Identity/Pages/Account/Login.cshtml.cs
  ChatRPG/Areas/Identity/Pages/Account/Register.cshtml
  ChatRPG/Areas/Identity/Pages/Account/Register.cshtml.cs
  ChatRPG/Areas/Identity/Pages/Shared/_LoginPartial.cshtml
  ChatRPG/Areas/Identity/RevalidatingIdentityAuthenticationStateProvider.cs
  ChatRPG/ChatRPG.csproj
  ChatRPG/Data/Models/Character.cs
  ChatRPG/Pages/ApiAccess.razor
  ChatRPG/Pages/Campaign.razor
  ChatRPG/Pages/OpenAiGptMessageComponent.razor
  ChatRPG/Pages/Shared/_Layout.cshtml
  ChatRPG/Pages/Shared/_LoginPartial.cshtml
  ChatRPG/Program.cs
  ChatRPG/Services/EfPersisterService.cs
  ChatRPG/Shared/NavMenu.razor
  ChatRPG/appsettings.json
Labels: enhancement

#48 Dashboard Campaign Deletion Modal
  ChatRPG/App.razor
  ChatRPG/ChatRPG.csproj
  ChatRPG/Pages/ConfirmModal.razor
  ChatRPG/Pages/UserCampaignOverview.razor
  ChatRPG/Pages/UserCampaignOverview.razor.cs
  ChatRPG/Pages/_Host.cshtml
  ChatRPG/Program.cs
  ChatRPG/Services/EfPersisterService.cs
  ChatRPG/Services/IPersisterService.cs
  ChatRPG/_Imports.razor
  ChatRPG/wwwroot/css/site.css
  ChatRPGTests/AuthorizedIndexE2ETests.cs
  ChatRPGTests/CampaignE2ETests.cs
  ChatRPGTests/E2ETestUtility.cs
Labels: enhancement

#59 add valid JSON requirement to sys prompts and fixed waitingForInput
  ChatRPG/Pages/CampaignPage.razor.cs
  ChatRPG/Services/GameInputHandler.cs
  ChatRPG/appsettings.json
Labels: Needs review

#51 Campaign page UI improvements
  ChatRPG/ChatRPG.csproj
  ChatRPG/Pages/CampaignPage.razor
  ChatRPG/Pages/CampaignPage.razor.cs
  ChatRPG/Pages/HealthBar.razor
  ChatRPG/Pages/OpenAiGptMessageComponent.razor
  ChatRPG/Pages/_Host.cshtml
  ChatRPG/_Imports.razor
  ChatRPG/wwwroot/css/site.css
  ChatRPG/wwwroot/js/detectScrollBar.js
  ChatRPGTests/AuthorizedIndexE2ETests.cs
Labels: enhancement

#60 Feature/improve npc descriptions
  ChatRPG/Pages/CampaignPage.razor
  ChatRPG/Pages/CampaignPage.razor.cs
  global.json
Labels: enhancement

#62 Campaign Page E2E Tests
  ChatRPG/API/OpenAiGptMessage.cs
  ChatRPG/Pages/CampaignPage.razor
  ChatRPG/Pages/OpenAiGptMessageComponent.razor
  ChatRPGTests/AuthorizedIndexE2ETests.cs
  ChatRPGTests/CampaignE2ETests.cs
  ChatRPGTests/ChatRPGFixture.cs
  ChatRPGTests/E2ETestUtility.cs
Labels: enhancement
