Repository KarmaKamikaze/ChatRPG, pull requests merged in 2024-11, with the labels that each got.

#102 BattleTool and full message collection instead of summary
  ChatRPG/API/ReActAgentChain.cs
  ChatRPG/API/ReActLlmClient.cs
  ChatRPG/API/Tools/BattleInput.cs
  ChatRPG/API/Tools/BattleTool.cs
  ChatRPG/API/Tools/CharacterInput.cs
  ChatRPG/API/Tools/EnvironmentInput.cs
  ChatRPG/API/Tools/HealCharacterTool.cs
  ChatRPG/API/Tools/ToolUtilities.cs
  ChatRPG/API/Tools/UpdateCharacterInput.cs
  ChatRPG/API/Tools/UpdateCharacterTool.cs
  ChatRPG/API/Tools/UpdateEnvironmentTool.cs
  ChatRPG/API/Tools/WoundCharacterTool.cs
  ChatRPG/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs
  ChatRPG/Areas/Identity/Pages/Account/Register.cshtml
  ChatRPG/Data/Models/Character.cs
  ChatRPG/Data/Models/CharacterType.cs
  ChatRPG/Pages/CampaignPage.razor
  ChatRPG/Pages/CampaignPage.razor.cs
  ChatRPG/Pages/Index.razor
  ChatRPG/Pages/Shared/_Layout.cshtml
  ChatRPG/Services/GameInputHandler.cs
  ChatRPG/Services/GameStateManager.cs
  ChatRPG/appsettings.json
Labels: enhancement

#108 Add skull icons to dead characters
  ChatRPG/Pages/CampaignPage.razor
  ChatRPG/Pages/CampaignPage.razor.cs
  ChatRPG/Pages/_Host.cshtml
  ChatRPG/Program.cs
  ChatRPG/Services/EfPersistenceService.cs
  ChatRPG/Services/JsInteropService.cs
  ChatRPG/wwwroot/css/site.css
Labels: bug, enhancement

#109 Hotfix/2.0.3
  ChatRPG/API/Tools/ToolUtilities.cs
  ChatRPG/appsettings.json
Labels: bug

#111 Reinclude Sarmi's changes
  ChatRPG/API/Tools/ToolUtilities.cs
  ChatRPG/appsettings.json
Labels: bug
